FROM python:3.7-slim-buster

RUN pip install pipenv-to-requirements

WORKDIR /app
COPY ./ ./

RUN pipenv_to_requirements && \
    pip install -r requirements.txt
RUN ls -la

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
