version: '3.3'

services:
  nginx:
    container_name: nginx
    image: weathertracker.azurecr.io/weather_tracker_nginx
    ports:
      - "1337:80"
  api:
    container_name: api
    image: weathertracker.azurecr.io/weather_tracker_api
    restart: always
  app:
    container_name: app
    image: weathertracker.azurecr.io/weather_tracker_app
    restart: always
