on: [push]
name: lolcounter container workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        - uses: azure/docker-login@v1
          with:
            login-server: weathertracker.azurecr.io
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build -t weathertracker.azurecr.io/weather_tracker_api:${{ github.sha }} -f Dockerfile.api .
            docker push weathertracker.azurecr.io/weather_tracker_api:${{ github.sha }}

            docker build -t weathertracker.azurecr.io/weather_tracker_app:${{ github.sha }} --build-arg REACT_APP_ENV=prod -f app/Dockerfile app/
            docker push weathertracker.azurecr.io/weather_tracker_app:${{ github.sha }}

            docker build -t weathertracker.azurecr.io/weather_tracker_nginx:${{ github.sha }} -f nginx/Dockerfile nginx/
            docker push weathertracker.azurecr.io/weather_tracker_nginx:${{ github.sha }}

        - name: Azure logout
          run: |
            az logout
